// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Communicator.proto
#ifndef GRPC_Communicator_2eproto__INCLUDED
#define GRPC_Communicator_2eproto__INCLUDED

#include "Communicator.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class Communicator final {
 public:
  static constexpr char const* service_full_name() {
    return "Communicator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status classify(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::ClassifyReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ClassifyReply>> Asyncclassify(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ClassifyReply>>(AsyncclassifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ClassifyReply>> PrepareAsyncclassify(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ClassifyReply>>(PrepareAsyncclassifyRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ClassifyReply>* AsyncclassifyRaw(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ClassifyReply>* PrepareAsyncclassifyRaw(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status classify(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::ClassifyReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ClassifyReply>> Asyncclassify(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ClassifyReply>>(AsyncclassifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ClassifyReply>> PrepareAsyncclassify(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ClassifyReply>>(PrepareAsyncclassifyRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::ClassifyReply>* AsyncclassifyRaw(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ClassifyReply>* PrepareAsyncclassifyRaw(::grpc::ClientContext* context, const ::ClassifyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_classify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status classify(::grpc::ServerContext* context, const ::ClassifyRequest* request, ::ClassifyReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_classify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_classify() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_classify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status classify(::grpc::ServerContext* context, const ::ClassifyRequest* request, ::ClassifyReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestclassify(::grpc::ServerContext* context, ::ClassifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::ClassifyReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_classify<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_classify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_classify() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_classify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status classify(::grpc::ServerContext* context, const ::ClassifyRequest* request, ::ClassifyReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_classify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_classify() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ClassifyRequest, ::ClassifyReply>(std::bind(&WithStreamedUnaryMethod_classify<BaseClass>::Streamedclassify, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_classify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status classify(::grpc::ServerContext* context, const ::ClassifyRequest* request, ::ClassifyReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedclassify(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ClassifyRequest,::ClassifyReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_classify<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_classify<Service > StreamedService;
};


#endif  // GRPC_Communicator_2eproto__INCLUDED
